from pydantic import BaseModel, Field


class Embedding(BaseModel):
    """
    Represents an embedding generated for a text chunk.

    This object contains the numerical vector generated by the
    embedding model along with information about the model used.

    The actual chunk text is stored separately in the Chunk object
    and later in the vector database. Therefore, we only keep the
    chunk_id here to avoid duplicating data in memory.
    """

    chunk_id: str

    vector: list[float] = Field(default_factory=list)

    model_name: str

    dimension: int

    def __str__(self):
        return (
            f"Embedding("
            f"chunk_id='{self.chunk_id}', "
            f"model='{self.model_name}', "
            f"dimension={self.dimension}"
            f")"
        )